#!/bin/bash
set -euxo pipefail
source /root/workshop/scripts/instruqt-workshop-helpers
ensure_services
copy_solution 02-first-workflow
start_worker 02-first-workflow workshop.TaglineWorker
temporal workflow start --type TaglineWorkflow --task-queue tagline-tasks \
  -w tagline-1 --input '"CatNip Cola"' --id-conflict-policy TerminateExisting
temporal workflow result -w tagline-1
